### ISSUE TITLE
Short description too long makes import to fail

### ISSUE THREAD

**Issue by gartempe** [161io/labodata-prestashop#1]
Hi,
It happens on some products, for instance CIP: 850803002714 / Labodata ID : 7411
The short description should be trimmed before importing it in Prestashop product.

Error message:
Property Product->description_short length (833) must be between 0 and 807 at line 961 in file classes/ObjectModel.php

**Comment by basselin** [comment]
Solution **views/templates/import/description_short.tpl**

`{$description_short|truncate:800:"..."}`

_This fix will be merged to the next version._

**Comment by gartempe** [comment]
Great. Thanks for the fast answer. 
I've just tested and it works.
